### PR TITLE
Comply fully with RFCs and allow a more structured XML configuration

### PR DESCRIPTION
**Pull request by luigiberrettini**
I refactored code to multiple classes having more specific responsibilities while sticking firmly to RFC specifications.
I then changed configuration to make it more structured and with separate sections, after having my modifications to NLog merged to its master (so that it can parse nodes with children).

### CODE REVIEW

**Comment by luigiberrettini** [comment]
Hi @graffen can you close the pull request if you do not want to merge it?

**Comment by graffen** [comment]
Hi @luigiberrettini 
Sorry I've been extremely busy for the last few weeks so I haven't had time to go through the PR yet. I'll try to go through the (many) commits as soon as possible, I promise :)

**Comment by luigiberrettini** [comment]
No problem: I am not in a hurry ;)
Thank you for the reply.

**Comment by thewetzel** [comment]
I am also interested in this pull request.

**Comment by graffen** [comment]
@luigiberrettini Thanks! Finally got a chance to look this one through. Nice work! I will push an updated NuGet package this evening.

**Comment by graffen** [comment]
Hi @luigiberrettini 
I will revert this PR on master since I think it would be better to bump the version number of the library for such big changes (API, configuration, documentation etc.). The previous version was pretty simple to get started with and supports most use-cases. However, I do think your changes have a lot of advantages so I don't want to just throw them away.

In addition a few issues have been reported that I need to look into but don't have the time to do so right now. So my plan is to put your work on a new 3.0-develop branch and see if we can get things stabilized and then do a re-release of the old 2.0 version in the mean time.

**Comment by Cottinet** [comment]
This PR was fixing issue #35 among other things. Since the PR is now in 3.0 dev branch, could it be possible to bring back only the fix in the master to have access to the fix before release of 3.0?
Thanks!

**Comment by davidgeary** [comment]
I can understand your reticence since this PR includes a significant number of changes, including new dependencies and refactoring.  (You're certainly right about it needing a version number increase.)  But like @Cottinet, it also fixes a couple of important issues for me with multiline messages and escaping invalid characters.

How about merging it into its own, separate branch first?  Then you could cherry-pick the straightforward/urgent fixes and merge them into the current v2 branch, so they can be released without having to wait for a review of the full PR.  The remaining commits could then be merged into the new v3 branch when it's more convenient.

**Comment by graffen** [comment]
Hmm, well I kind of agree that this would be the best way to do it. On my local machine I've started picking the git repo apart, trying to get it into a more logically sane state. 

I have reset master back to v2.1.5893.18660. 
I have a separate branch called current-release-cleanup which just contains the currently released version with the rolled-back merge commits etc.) while I clean up everything. This branch will go away once we're done. 
I have 3.0-develop containing the full PR from @luigiberrettini 
And finally I have a cherrypick-fixes off master which I will use to cherrypick the relevant changes. It's a little hard to see from the commit log which commits affect #35 specifically though so I'll do my best :)

I'll do a (ugh!) force push of the current state of my repo now, so everyone can see where we are. The way I see it, it's the only way we can get everything neatly back in sync.

**Comment by thewetzel** [comment]
I believe d4cebc6 is the most relevant commit that fixes the timestamp issue #35, but it includes a lot of structural changes also. I think you can change line 240 in NLog.Targets.Syslog.cs from:
`var time = logEvent.TimeStamp.ToString("o");`
to:
`var time = string.Format(CultureInfo.InvariantCulture, "{0:yyyy-MM-ddTHH:mm:ss.ffffffK}", logEvent.TimeStamp);`

Please forgive my contribution in this way. I don't really have any experience Github or pull requests, nor with C#.

**Comment by graffen** [comment]
@thewetzel Thanks, that was also the line I had singled in on for that specific issue. I'll get it fixed and pushed tonight when I get home from work, hopefully.

**Comment by luigiberrettini** [comment]
Hi, sorry for not having created tiny commits :(
I agree with the version 3 idea; my only concern is where to find the NuGet package related to my PR: did you revert also the published NuGet package and if so have you published a beta package?

Thanks!

**Comment by graffen** [comment]
@luigiberrettini I didn't get a chance to publish a beta version yesterday. I'll try to get it done ASAP (I'm not home an awful lot these days so my time spent in front of my windows PC at home is quite limited).

**Comment by luigiberrettini** [comment]
This way you are broking build of all the people who used it without offering an alternative: it would be better not to unlist it until you publish a beta package.

**Comment by graffen** [comment]
@luigiberrettini I agree that I could probably have handled this better from the beginning. Your changes should not have been merged to master immediately but should have gone directly to a vNext branch and allowed to stabilize and mature before merging them to master. And judging from the amount of support emails I was getting, de-listing the "broken" (for lack of a better word) version was the easiest solution in the short term. I have been asking folks to create issues here on Github but not a lot have done so unfortunately.

**Comment by luigiberrettini** [comment]
I am sorry for you and for people who do not understand how open-source work (writing e-mails instead of opening issues).

**Comment by luigiberrettini** [comment]
Moved from milestone 2.1.6015.35897 to milestone 3.0.0

**Pull request merged**
