### PR TITLE
AppVeyor support

### PR DESCRIPTION
**Pull request by 304NotModified**
I saw this project isn't running on a build server. AppVeyor is a free (for OSS) buildserver for .NET 

At NLog we are very happy with AppVeyor. Therefor I prepared the project for AppVeyor:

- enabled nuget package restore
- enabled nuget package building (

See result for my fork: https://ci.appveyor.com/project/304NotModified/nlog-targets-syslog/build/1.0.8

To set-up AppVeyor:

1. login with AppVeyor (with GitHub account)
2. create new project
3. select this repos.
4. Done

After this, every PR will be automatically build by AppVeyor. 

In the future you could add some unit tests which will be also run by AppVeyor

### CODE REVIEW

**Comment by 304NotModified** [comment]
If you have any questions about this, just let me know :)

**Comment by luigiberrettini** [comment]
Some questions:

1. NuGet push is still manual in your appveyor.yml, am I right?
2. Don't we need to [setup a webhook](http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests#comment_33212404) to build PRs?

**Comment by 304NotModified** [comment]
1 yes it's a manual action
2 that will be automatically created
3 testing it before release and push it from appveyor to nuget.org (manual action). You could release from your phone :)

**Comment by luigiberrettini** [comment]
With semantic versioning I bump NuGet version in the YML: will PR builds always create the same version of the package with me publishing manually only the one that I choose?

**Comment by 304NotModified** [comment]
It will create the version defined in the yml. You could also publish older nuget packages (=older build) if you need that.

**Pull request merged**
