### PR TITLE
Refactor and clean-up

### PR DESCRIPTION
**Pull request by luigiberrettini**
Disable ReSharper suggestions
Remove this.
Same XML comment structure for each node (included summary)
Extract some methods
Move conversion from NLog log level to a class implementing the syslog severity enumeration

### CODE REVIEW

**Comment by graffen** [comment]
Beautiful PR, thanks! :)

**Comment by luigiberrettini** [comment]
Thank YOU for this amazing target ;)

Forgive the naive question: the NLog.Targets.Syslog NuGet package will be updated automatically?

**Comment by graffen** [comment]
The nuget package will get updated tonight (Denmark time) :)

**Comment by luigiberrettini** [comment]
Thanks a lot!

**Comment by graffen** [comment]
v2.1.5889.34458 is now published on NuGet :)

**Pull request merged**
