### PR TITLE
Creates method to find the entry assembly for web projects

### PR DESCRIPTION
**Pull request by mniak**
Fix for issue #49 as I've commented

### CODE REVIEW

**Comment by 304NotModified** [comment]
without a build server / unit test, it's also a bit guessing ;) 

but I think this works well as this `Assembly.GetEntryAssembly();` is the first try (which is backwards compatible).

@mniak Maybe we should also implement this in NLog, see https://github.com/NLog/NLog/issues/275

**Comment by luigiberrettini** [comment]
Replaced by #53

**Comment by mniak** [comment]
Sorry for the missing tests, I'm just not experienced with creatin tests and contributing

**Comment by luigiberrettini** [comment]
Do not worry @mniak, @304NotModified was referring to the target codebase.
He is right and we should find time to add tests to have behavior covered and avoid regressions.
Anyway IMHO it would have been quite complex to implement a test that simulates being a web app.

TDD is not about testing but uses tests to design your application and you also have user scenarios covered.
Here are some references useful to start a learning journey 😉
http://www.amazon.com/dp/0201485672
http://www.amazon.com/dp/0321213351
http://www.amazon.com/dp/0132350882
http://www.amazon.com/dp/0321146530
http://www.amazon.com/dp/0321503627
http://www.jamesshore.com/Blog/Lets-Play

**Comment by 304NotModified** [comment]
> Sorry for the missing tests, I'm just not experienced with creating tests and contributing.

About the tests, I would recommend to start here: https://xunit.github.io/docs/getting-started-desktop.html

Very easy to start with

**Comment by mniak** [comment]
@luigiberrettini Ok, now I feel better 😂. Thanks for the references!

@304NotModified I was unclear. I know how to create unit tests. I meant that I don't know how to test some behaviors, for instance those which uses I/O, and I've never built a completely testable project.

**Pull request closed without merging**
